//! The segmenting and crossfade around the model.
//!
//! The end-to-end check needs a 21 MB fixture, so it is an ignored test reading
//! `STEMD_MLX_FIXTURES`, generated by `tools/eval/make_apply_fixture.py`.
//!
//! What runs by default: the window protocol on a track shorter than one segment,
//! and a track with a sample no segment covers.

mod common;

use common::{array, null_db, one_at_a_time, weights};
use mlx_rs::ops;
use mlx_rs::ops::indexing::IndexOp;
use stemd_mlx::apply::{DEFAULT_OVERLAP, over_track};
use stemd_mlx::htdemucs::{Config, HtDemucs};

/// A track shorter than one segment still goes through the window protocol.
///
/// "With one segment there is nothing to crossfade, so segmenting must equal a
/// plain forward" is false. `valid_length` returns the training length whatever it
/// is handed, so even a one-second track is centred inside a full 7.8-second
/// window, zero-padded either side, and recovered with a centre trim. A plain
/// `forward` pads on the right instead, as the reference's `__call__` does.
///
/// So what is asserted is the protocol: build the centred window by hand, run it,
/// trim it, and require the segmenting path to agree.
#[test]
fn a_short_track_is_centred_in_its_window() {
    let _gpu = one_at_a_time();
    let Some(w) = weights() else { return };

    let config = Config::default();
    let segment = config.training_length();
    let direct = HtDemucs::load(&w, "model_0", config).expect("loading htdemucs");

    let input = array("model_input");
    let length = *input.shape().last().expect("a last axis");
    assert!(
        length < segment,
        "this test needs a track under one segment"
    );

    let (centred, left) = centre(&input, segment);
    let want = direct
        .forward(&centred)
        .expect("forward")
        .index((.., .., .., left..left + length));

    let got = over_track(&direct, &input, DEFAULT_OVERLAP, &mut |_, _| Ok(()))
        .expect("through the segmenting path");

    assert_eq!(got.shape(), want.shape(), "shape differs");
    let null = null_db(&got, &want);
    println!("short-track null: {null:.1} dB");
    assert!(
        null < -100.0,
        "segmenting differs from the centred window by {null:.1} dB"
    );
}

/// A track padded out to a full window, plus where the real audio starts in it.
fn centre(input: &mlx_rs::Array, segment: i32) -> (mlx_rs::Array, i32) {
    let length = *input.shape().last().expect("a last axis");
    let delta = segment - length;
    let (left, right) = (delta / 2, delta - delta / 2);
    let padded = ops::pad(
        input,
        &[(0, 0), (0, 0), (left, right)][..],
        mlx_rs::Array::from_f32(0.0),
        None,
    )
    .expect("centring the window");
    (padded, left)
}

/// Every sample must be covered by at least one segment, and the joins must be
/// crossfades rather than cuts.
///
/// Not "the weights sum to a constant": with a stride of three quarters of a
/// segment and a triangular window the sum ripples 2:1 by design, and dividing by
/// it is what flattens it. What has to hold is that the sum is never zero and that
/// adjacent segments overlap.
#[test]
fn every_sample_is_covered_and_the_joins_overlap() {
    let _gpu = one_at_a_time();

    // The shape of the weight is what matters, not its length, so this runs the
    // real arithmetic at a size that needs no model.
    let segment = 1000;
    let stride = ((1.0 - DEFAULT_OVERLAP) * segment as f32) as i32;
    let half = segment / 2;
    let values: Vec<f32> = (1..=half)
        .map(|i| i as f32)
        .chain((1..=segment - half).rev().map(|i| i as f32))
        .collect();
    let peak = values.iter().copied().fold(f32::MIN, f32::max);
    let weight: Vec<f32> = values.iter().map(|v| v / peak).collect();

    let length = segment * 4;
    let mut sum = vec![0.0f32; length as usize];
    let mut covers = vec![0u32; length as usize];
    let mut offset = 0;
    while offset < length {
        let usable = (length - offset).min(segment);
        for i in 0..usable {
            sum[(offset + i) as usize] += weight[i as usize];
            covers[(offset + i) as usize] += 1;
        }
        offset += stride;
    }

    let smallest = sum.iter().copied().fold(f32::MAX, f32::min);
    println!("smallest weight sum: {smallest:.4}");
    assert!(
        smallest > 0.0,
        "some sample is covered by no segment, so the division would be undefined"
    );

    // The overlap is a quarter of a segment, so a quarter of the track either
    // side of each join should see two segments. Without that the crossfade is
    // a cut with extra steps.
    let overlapped = covers.iter().filter(|&&c| c >= 2).count();
    println!("samples covered by two or more segments: {overlapped}");
    assert!(
        overlapped > 0,
        "no sample is covered twice, so nothing is being crossfaded"
    );
}

/// The whole path over a track that needs three segments.
///
/// The reference's `valid_length` returns the training length whatever it is
/// given, so the last, short chunk is still fed a full-width window centred on its
/// offset, and the useful part is recovered with a centre trim. Taking the output
/// from index zero instead puts the final segment half the shortfall early, which
/// nulls at -4 dB.
///
/// Ignored because its fixture is 21 MB:
/// `STEMD_MLX_WEIGHTS=... STEMD_MLX_FIXTURES=... cargo test -p stemd-mlx -- --ignored`
#[test]
#[ignore]
fn a_whole_track_matches_the_reference() {
    let _gpu = one_at_a_time();
    let Some(w) = weights() else { return };
    let Ok(dir) = std::env::var("STEMD_MLX_FIXTURES") else {
        eprintln!(
            "SKIPPED: set STEMD_MLX_FIXTURES to the directory holding apply_input/apply_output"
        );
        return;
    };

    let load = |name: &str| -> mlx_rs::Array {
        let dir = std::path::Path::new(&dir);
        let shape: Vec<i32> = std::fs::read_to_string(dir.join(format!("{name}.shape")))
            .expect("shape")
            .split_whitespace()
            .map(|d| d.parse().expect("integers"))
            .collect();
        let bytes = std::fs::read(dir.join(format!("{name}.f32"))).expect("data");
        let data: Vec<f32> = bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect();
        mlx_rs::Array::from_slice(&data, &shape)
    };

    let model = HtDemucs::load(&w, "model_0", Config::default()).expect("loading htdemucs");
    let input = load("apply_input");
    let s = input.shape().to_vec();
    let input = input.reshape(&[1, s[0], s[1]]).expect("add a batch axis");

    let got = over_track(&model, &input, DEFAULT_OVERLAP, &mut |done, total| {
        if done < total {
            eprintln!("  segment {}/{total}", done + 1);
        }
        Ok(())
    })
    .expect("separating the track");

    let want = load("apply_output");
    assert_eq!(got.shape(), want.shape(), "shape differs");
    let null = null_db(&got, &want);
    println!("whole track null: {null:.1} dB");
    assert!(null < -60.0, "the track nulls at only {null:.1} dB");
    let _ = ops::abs(&got);
}
